version: "3.9"
services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=development
  redis:
    image: redis:alpine
    command: >
      --requirepass mysecretpassword
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "4000:4000"
    environment:
      - DB_URI=postgres://postgres:mysecretpassword@postgres:5432/development?sslmode=disable
      - REDIS_HOST=redis
      - REDIS_PASSWORD=mysecretpassword
    depends_on:
      - postgres
      - redis
    entrypoint: [ "sh", "/app/wait-for.sh", "postgres:5432", "--", "sh", "/app/start.sh", "--" ]
    command: [ "/app/main" ]