name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run migrations
        run: make testmigrateup
        env:
          TEST_DB_URI: postgresql://postgres:mysecretpassword@postgres:5432/test?sslmode=disable

      - name: Test
        run: make test
        env:
          TEST_DB_URI: postgresql://postgres:mysecretpassword@postgres:5432/test?sslmode=disable
